### ISSUE TITLE
Update Bash Script to Download Files - Checkpoint 2

### ISSUE THREAD

**Issue by jtsmedley** [jtsmedley/WebSync#2]
Requires that issue #1 is completed.

The bash script needs the ability to download the requested files and place it in the path specified in the config files format found in the README.md.  Modify the script to download the file and add console logging to show that the file is being downloaded and has been downloaded.

**Comment by jtsmedley** [comment]
#2 handled by #1

**Comment by LokiMetaSmith** [comment]
done!
